### ISSUE TITLE
使用NWPU数据训练报错

### ISSUE THREAD

**Issue by daibin88** [TencentYoutuResearch/CrowdCounting-P2PNet#18]
使用NWPU数据集训练时出现如下错误，使用ShanghaiTech PartA ,PartB训练OK
Start training
Traceback (most recent call last):
  File "train.py", line 222, in <module>
    main(args)
  File "train.py", line 159, in main
    stat = train_one_epoch(
  File "/home/model/CrowdCounting-P2PNet/engine.py", line 85, in train_one_epoch
    for samples, targets in data_loader:
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1183, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.8/dist-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 6.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/model/CrowdCounting-P2PNet/crowd_datasets/SHHA/SHHA.py", line 73, in __getitem__
    img, point = random_crop(img, point)
  File "/home/model/CrowdCounting-P2PNet/crowd_datasets/SHHA/SHHA.py", line 133, in random_crop
    idx = (den[:, 0] >= start_w) & (den[:, 0] <= end_w) & (den[:, 1] >= start_h) & (den[:, 1] <= end_h)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by Tracyummy** [comment]
有空图片

**Comment by Tracyummy** [comment]
有空图片

**Comment by daibin88** [comment]
> 有空图片

NWPU中的空图片应该是为了减少误检使用的，代码中怎么不支持？

**Comment by fyw1999** [comment]
改了空图片的问题以后又报错“Invalid SOS parameters for sequential JPEG”，这又是怎么了，不知道原文是怎么在nwpu上训练的。
