### ISSUE TITLE
Error in checking torchvision.__version__ with double digits in util/misc.py

### ISSUE THREAD

**Issue by mfatiho** [TencentYoutuResearch/CrowdCounting-P2PNet#27]
Traceback (most recent call last):
        File "/home/mfo/Projects/crowd-counting-gui/demo_gui.py", line 16, in <module>
          from models import build_model
        File "/home/mfo/Projects/crowd-counting-gui/CrowdCounting-P2PNet/models/__init__.py", line 1, in <module>
          from .p2pnet import build
        File "/home/mfo/Projects/crowd-counting-gui/CrowdCounting-P2PNet/models/p2pnet.py", line 5, in <module>
          from util.misc import (NestedTensor, nested_tensor_from_tensor_list,
        File "/home/mfo/Projects/crowd-counting-gui/CrowdCounting-P2PNet/util/misc.py", line 26, in <module>
          from torchvision.ops import _new_empty_tensor
      ImportError: cannot import name '_new_empty_tensor' from 'torchvision.ops' (/home/mfo/miniconda3/envs/p2pnet/lib/python3.9/site-packages/torchvision/ops/__init__.py)

**Comment by KunMengcode** [comment]
@mfatiho This issue is related to the version of Torchvision, and I have not yet explored the actual details. But I solved it.
In the `util/misc.py` file, search for `torchvision.__version__[:3] ` A total of two locations can be found, changing `<0.7` to `>0.7`
